/// Generate [classPrefix]Event that extends FastBlocEvent and [classPrefix]State that extends FastBlocState.
/// Generate a series of [events] classes that extends [classPrefix]Event along static methods to instantiate them.
/// E.g. to generate a MyBlocEvent and MyBlocState:
/// ```dart
/// @BlocEventState('MyBloc', [
///   BlocEventDetail('event1', params: {Param<int>('myIntParam'), Param<String?>('myNullableStringParam'), Param<MyClass>('myClassParam')}),
///   BlocEventDetail('event2', params: {Param<int>('myIntParam')}),
///   BlocEventDetail('event3'),
/// ], state: {
///   Param<int>('var1'),
///   Param<String?>('var2'),
/// })
/// ```
class BlocEventState {
  final String classPrefix;
  final List<BlocEvent> events;
  final Set<Param<dynamic>>? state;

  /// Generate [classPrefix]Event that extends FastBlocEvent and [classPrefix]State that extends FastBlocState.
  /// Generate a series of [events] classes that extends [classPrefix]Event along static methods to instantiate them.
  /// E.g. to generate a MyBlocEvent and MyBlocState:
  /// ```dart
  /// @BlocEventState('MyBloc', [
  ///   BlocEventDetail('event1', params: {Param<int>('myIntParam'), Param<String?>('myNullableStringParam'), Param<MyClass>('myClassParam')}),
  ///   BlocEventDetail('event2', params: {Param<int>('myIntParam')}),
  ///   BlocEventDetail('event3'),
  /// ], state: {
  ///   Param<int>('var1'),
  ///   Param<String?>('var2'),
  /// })
  /// ```
  const BlocEventState(this.classPrefix, this.events, {this.state});
}

/// Represent an event class [eventName] that extends the class generated by [Bloc].
/// [params] is a map with the name of the parameter as key and its type as value.
/// ```dart
/// BlocEventDetail('event', params: {Param<int>('myIntParam'), Param<String?>('myNullableStringParam'), Param<MyClass>('myClassParam')}),
/// ```
class BlocEvent {
  final String eventName;
  final Set<Param<dynamic>>? params;

  /// Represent an event class [eventName] that extends the class generated by [Bloc].
  /// [params] is a map with the name of the parameter as key and its type as value.
  /// ```dart
  /// BlocEventDetail('event', params: {Param<int>('myIntParam'), Param<String?>('myNullableStringParam'), Param<MyClass>('myClassParam')}),
  /// ```
  const BlocEvent(this.eventName, {this.params});
}

class Param<T> {
  final String name;
  const Param(this.name);
}
